/**
 * @file server.ts
 * @description Main server entry point with HTTP, WebSocket, and cluster setup
 * @module server
 *
 * Initializes and configures the complete server stack:
 * - HTTP server: Express-like API with middleware
 * - ArangoDB: Database connection and configuration
 * - WebSocket: Real-time collaboration server
 * - ClusterManager: Distributed node coordination
 * - Request handlers: Workflow, category, builder, data type, sync, node config
 *
 * Key features:
 * - Command line argument parsing for configuration
 * - CORS and rate limiting middleware
 * - Error handling middleware
 * - Development mode with Vite integration
 * - Cluster communication via ZeroMQ
 * - Global database instance export
 */

import {cors, HttpServer, logger, NextFunction, rateLimit, Response, Request} from "./http/HttpServer";
import { spawn } from "child_process";
import {parseArgs} from "./utils/env";
import {Database} from "arangojs";
import {ClusterManager, ClusterNode} from "./cluster/clusterManager";
import {WebSocketManager, WebSocketManagerOptions} from "./cluster/webSocketManager";
import {RequestWorkFlow} from "./request/requestWorkFlow";
import {RequestCategory} from "./request/requestCategory";
import {RequestBuilder} from "./request/requestBuilder";
import {RequestDataType} from "./request/requestDataType";
import {RequestSync} from "./request/requestSync";
import {RequestNodeConfig} from "./request/requestNodeConfig";
import { writeFileSync, readFileSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { loadOrGenerateCert } from './utils/generateCert';

const args =  parseArgs();

// Auto-generate .env file for Vite
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const host = args.get('host', 'localhost');
const port = args.get('port', '8426');

// HTTPS configuration
const useHttps = args.get('https', 'false') === 'true';
const certPath = args.get('cert', '');
const keyPath = args.get('key', '');

// Load or generate SSL certificates if HTTPS is enabled
let httpsConfig: { key: string; cert: string } | undefined;
if (useHttps) {
    if (certPath && keyPath) {
        // Use provided certificate files
        if (!existsSync(certPath) || !existsSync(keyPath)) {
            console.error(`Certificate files not found: cert=${certPath}, key=${keyPath}`);
            process.exit(1);
        }
        httpsConfig = {
            key: readFileSync(keyPath, 'utf-8'),
            cert: readFileSync(certPath, 'utf-8')
        };
        console.log(`Using provided SSL certificate from ${certPath}`);
    } else {
        // Generate self-signed certificate (async)
        console.log(`Generating self-signed SSL certificate...`);
        httpsConfig = await loadOrGenerateCert({
            commonName: host,
            outputDir: join(__dirname, '..', '..', 'certs')
        });
    }
}

const protocol = useHttps ? 'https' : 'http';
const apiUrl = `${protocol}://${host}:${port}`;

// WebSocket URL configuration
const wsProtocol = useHttps ? 'wss' : 'ws';
const wsUrl = useHttps
    ? `${wsProtocol}://${host}:${port}/ws`  // WSS uses same port with /ws path
    : `${wsProtocol}://${host}:${parseInt(port) + 2000}`;  // WS uses separate port

const envContent = `# Auto-generated by server.ts at startup
# Do not edit manually - this file is regenerated on each server start
# To change the API URL, modify the server start command arguments

# API Configuration
VITE_API_URL=${apiUrl}

# WebSocket Configuration
VITE_WS_URL=${wsUrl}

# HTTPS Configuration
VITE_USE_HTTPS=${useHttps}
`;

const envPath = join(__dirname, '..', '..', '.env');
writeFileSync(envPath, envContent, 'utf-8');
console.log(`✅ Generated .env file with API URL: ${apiUrl}`);


// Database configuration
const dbUrl = args.get("arangodb", "http://127.0.0.1:8529");
const dbUser = args.get("arangodb_user", "root");
const dbPass = args.get("arangodb_pass", "azerty");
const dbName = args.get("arangodb_name", "nodius");

// Initialize database (create if doesn't exist)
async function initializeDatabase() {
    // First connect to _system database to check/create target database
    const systemDb = new Database({
        url: dbUrl,
        auth: { username: dbUser, password: dbPass },
        databaseName: '_system'
    });

    try {
        const databases = await systemDb.listDatabases();

        if (!databases.includes(dbName)) {
            console.log(`📝 Database "${dbName}" does not exist, creating...`);
            await systemDb.createDatabase(dbName);
            console.log(`✅ Database "${dbName}" created successfully`);
        } else {
            console.log(`✅ Database "${dbName}" exists`);
        }
    } catch (error) {
        console.error(`❌ Failed to initialize database: ${error}`);
        throw error;
    }
}

// Initialize database before creating connection
await initializeDatabase();

export const db = new Database({
    url: dbUrl,
    auth: { username: dbUser, password: dbPass },
    databaseName: dbName
});

const app = new HttpServer();
app.use(logger());
app.use(cors());
app.use(rateLimit({ windowMs: 60000, max: 100 }));

// Error handling middleware
app.use((err: Error, req: Request, res: Response, next: NextFunction) => {
    console.error('Error:', err.message);
    console.trace(err);
    res.status(500).json({ error: err.message });
});

// Export configuration early (needed by other modules)
export const peerHost = args.get("host");
export const peerPort = parseInt(args.get("port"));
export { useHttps };
export const clusterManagerPort = peerPort + 1000;
export const webSocketPort = peerPort + 2000;

// Initialize routes before starting server
RequestWorkFlow.init(app);
RequestCategory.init(app);
RequestBuilder.init(app);
RequestDataType.init(app);
RequestSync.init(app);
RequestNodeConfig.init(app);

// Start server with proper options
const serverOptions: { port: number; host: string; https?: { key: string; cert: string } } = {
    port: parseInt(args.get("port", "8426")),
    host: args.get("host", "localhost"),
};

if (httpsConfig) {
    serverOptions.https = httpsConfig;
}

// Initialize cluster manager
export const clusterManager = new ClusterManager(clusterManagerPort, peerHost);

// WebSocketManager will be initialized after server starts
export let webSocketManager: WebSocketManager;

// Start the server and then initialize WebSocket
await app.listen(serverOptions);
console.log(`Server is ready! (${useHttps ? 'HTTPS' : 'HTTP'})`);

// Now create WebSocketManager - server is guaranteed to be running
if (useHttps) {
    // Get the underlying HTTPS server and attach WebSocket to it
    const server = app.getServer();
    if (server) {
        webSocketManager = new WebSocketManager({
            server: server,
            path: '/ws'
        });
        console.log(`WebSocket server attached to HTTPS server at wss://${peerHost}:${peerPort}/ws`);
    } else {
        // This should not happen now
        console.error('HTTPS server not available after listen(), this is a bug');
        process.exit(1);
    }
} else {
    // HTTP mode: standalone WebSocket server on separate port
    webSocketManager = new WebSocketManager(webSocketPort, peerHost);
}

// Initialize cluster
clusterManager.initialize();

// Start Vite in development mode
if(args.get("mode", "production") == "development") {
    const proc = spawn("npx", ["vite"], { stdio: "pipe", shell: true });
    proc.stdout.on("data", (data) => {
        process.stdout.write(data);
    });

    proc.stderr.on("data", (data) => {
        process.stderr.write(data);
    });
}

clusterManager.on("broadcast", (payload:any, sender:string) => {
    console.log("received broadcast from sender", sender, "with payload", payload);
});

clusterManager.on("directMessage", (payload:any, sender:string) => {
    console.log("received message from sender", sender, "with payload", payload);
});

process.on('SIGINT', async () => {
    console.log('Caught SIGINT, shutting down...');
    await clusterManager.shutdown();
    webSocketManager.closeServer();
    process.exit(0);
});

process.on('SIGTERM', async () => {
    console.log('Caught SIGTERM, shutting down...');
    await clusterManager.shutdown();
    webSocketManager.closeServer();
    process.exit(0);
});

process.on('beforeExit', async () => {
    console.log('Process beforeExit, cleaning up...');
    await clusterManager.shutdown();
    webSocketManager.closeServer();
});