// Get user arguments (excluding node and script path)
import {writeFileSync} from "node:fs";
import {join} from "node:path";
import {dirname} from "path";
import {fileURLToPath} from "url";
import {spawn} from "node:child_process";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const args = process.argv.slice(2);

// Helper function to parse key=value strings into an object
const parseArgs = (args) => {
    const result = {};
    args.forEach(arg => {
        const [key, value] = arg.split('=');
        if (key && value !== undefined) {
            // Convert common string booleans and numbers
            if (value === 'true') result[key] = true;
            else if (value === 'false') result[key] = false;
            else if (!isNaN(value) && value !== '') result[key] = Number(value);
            else result[key] = value;
        }
    });
    return result;
};

const config = parseArgs(args);

// Now assign to variables with default values
const port = config.port !== undefined ? config.port : 8426;
const host = config.host || 'localhost';
const https = config.https || false;

const protocol = https ? 'https' : 'http';
const apiUrl = `${protocol}://${host}:${port}`;

// WebSocket URL configuration
const wsProtocol = https ? 'wss' : 'ws';
const wsUrl = https
    ? `${wsProtocol}://${host}:${port}/ws`  // WSS uses same port with /ws path
    : `${wsProtocol}://${host}:${parseInt(port) + 2000}`;  // WS uses separate port

const envContent = `
# Auto-generated by server.ts at startup
# Do not edit manually - this file is regenerated on each server start
# To change the API URL, modify the server start command arguments

# API Configuration
VITE_API_URL=${apiUrl}

# WebSocket Configuration
VITE_WS_URL=${wsUrl}

# HTTPS Configuration
VITE_USE_HTTPS=${https}
`;

const envPath = join(__dirname, '..', '.env');
writeFileSync(envPath, envContent, 'utf-8');
console.log(`✅ Generated .env file with API URL: ${apiUrl}`);

const proc = spawn("npx", ["vite"], { stdio: "pipe", shell: true });
proc.stdout.on("data", (data) => {
    process.stdout.write(data);
});

proc.stderr.on("data", (data) => {
    process.stderr.write(data);
});